# Generated by Django 5.2.7 on 2025-11-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha_venta'], 'verbose_name': 'Venta/Pedido', 'verbose_name_plural': 'Ventas/Pedidos'},
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PAG', 'Pagado'), ('ENT', 'En Tránsito'), ('OK', 'Entregado'), ('CAN', 'Cancelado')], default='PAG', help_text='Estado actual de la transacción y envío', max_length=3),
        ),
    ]
