# Generated by Django 5.2.7 on 2025-11-08 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_options_alter_venta_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_garantia', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('EXP', 'Expirada'), ('REC', 'Reclamada')], default='ACT', max_length=3)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='ventas.detalleventa')),
            ],
            options={
                'verbose_name': 'Garantía de Producto',
                'verbose_name_plural': 'Garantías de Producto',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
    ]
