# Generated by Django 5.2.7 on 2025-11-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='motivo_reclamo',
            field=models.TextField(blank=True, help_text='Descripción del cliente sobre la falla', null=True),
        ),
        migrations.AddField(
            model_name='garantia',
            name='observacion_admin',
            field=models.TextField(blank=True, help_text='Notas del administrador sobre la revisión o rechazo', null=True),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activa'), ('REC', 'Reclamo Iniciado'), ('REV', 'En Revisión'), ('APR', 'Aprobada'), ('RZD', 'Rechazada'), ('EXP', 'Expirada')], default='ACT', max_length=3),
        ),
    ]
