# Generated by Django 5.2.7 on 2025-10-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad del usuario. Opcional en el registro.', null=True),
        ),
    ]
