# Generated by Django 5.2.7 on 2025-10-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre corto del producto (Ej: Refrigerador)', max_length=100)),
                ('marca', models.CharField(help_text='Fabricante (Ej: Samsung, LG)', max_length=50)),
                ('modelo', models.CharField(blank=True, help_text='Modelo específico del fabricante', max_length=50, null=True)),
                ('categoria', models.CharField(help_text='Ej: Refrigeración, Cocción, Lavado, Audio/TV', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de venta actual', max_digits=10)),
                ('stock', models.IntegerField(default=0, help_text='Unidades disponibles en inventario')),
                ('garantia_meses', models.IntegerField(default=12, help_text='Meses de garantía estándar (Ej: 12, 24)')),
            ],
            options={
                'verbose_name': 'Electrodoméstico',
                'verbose_name_plural': 'Electrodomésticos',
            },
        ),
    ]
