# Generated by Django 5.2.7 on 2025-10-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de la imagen alojada en la nube (e.g., Cloudinary).', max_length=500, null=True),
        ),
    ]
