# Generated by Django 5.2.7 on 2025-10-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nit_ci',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
