# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations
import os # Importa os para leer variables de entorno

def crear_superusuario(apps, schema_editor):
    """
    Crea un superusuario administrador si no existe uno.
    Lee las credenciales desde variables de entorno.
    """
    # Obtiene el modelo Usuario personalizado
    Usuario = apps.get_model('usuario', 'Usuario') # Usa ('nombre_app', 'NombreModelo')

    ADMIN_USERNAME = os.environ.get('DJANGO_ADMIN_USERNAME', 'admin') # Default 'admin' si no se define
    ADMIN_EMAIL = os.environ.get('DJANGO_ADMIN_EMAIL', 'admin@example.com') # Default email si no se define
    ADMIN_PASSWORD = os.environ.get('DJANGO_ADMIN_PASSWORD') # ¡Esta DEBE definirse en Render!
    ADMIN_ROL = 'ADM' # Rol específico que quieres

    # Verifica si ya existe un superusuario con ese username o email
    # O si ya existe algún superusuario (is_superuser=True)
    if not Usuario.objects.filter(username=ADMIN_USERNAME).exists() and \
       not Usuario.objects.filter(email=ADMIN_EMAIL).exists() and \
       not Usuario.objects.filter(is_superuser=True).exists():

        if not ADMIN_PASSWORD:
            print("\nADVERTENCIA: No se definió DJANGO_ADMIN_PASSWORD en las variables de entorno. No se creará el admin.")
            return # No continuar si no hay contraseña

        print(f"\nCreando superusuario inicial: {ADMIN_USERNAME} ({ADMIN_EMAIL}) con rol {ADMIN_ROL}")
        Usuario.objects.create_superuser(
            username=ADMIN_USERNAME,
            email=ADMIN_EMAIL,
            password=ADMIN_PASSWORD,
            rol=ADMIN_ROL # Asigna el rol personalizado aquí
        )
        print("Superusuario creado exitosamente.")
    else:
        print("\nUn superusuario ya existe. Omitiendo creación.")


class Migration(migrations.Migration):

    dependencies = [
        # Asegúrate que esta dependencia sea la migración ANTERIOR de tu app 'usuario'
        # (o la migración inicial de Django si es la primera vez)
        ('usuario', '0001_initial'), # AJUSTA '0001_initial' al nombre de tu última migración de usuario
    ]

    operations = [
        migrations.RunPython(crear_superusuario),
    ]