# Generated by Django 5.2.7 on 2025-10-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_cliente_nit_ci'),
        ('usuario', '0007_crear_admin_inicial'),
    ]

    operations = [
    ]
