# Generated by Django 5.2.7 on 2025-11-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_merge_0006_cliente_nit_ci_0007_crear_admin_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria_antigua',
            field=models.CharField(blank=True, help_text='Ej: Refrigeración, Cocción, Lavado, Audio/TV', max_length=50, null=True),
        ),
    ]
