# Generated by Django 5.2.7 on 2025-11-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_categoria_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria_antigua',
        ),
    ]
