# Generated by Django 5.2.7 on 2025-11-08 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_carrito_itemcarrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre de la promoción (Ej: 'Venta Flash de Verano')", max_length=255)),
                ('tipo_descuento', models.CharField(choices=[('PCT', 'Porcentaje'), ('FIJ', 'Monto Fijo (Bs)')], help_text='Si el descuento es un % o un monto fijo.', max_length=3)),
                ('valor_descuento', models.DecimalField(decimal_places=2, help_text="El valor (ej: '15' para 15% o '50' para 50 Bs)", max_digits=10)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, help_text='Cuándo empieza la promoción.')),
                ('fecha_fin', models.DateTimeField(help_text='Cuándo termina la promoción.')),
                ('activo', models.BooleanField(default=True, help_text='Activa o desactiva la promoción globalmente.')),
                ('categorias', models.ManyToManyField(blank=True, help_text='Aplica esta promoción a todos los productos de estas categorías.', related_name='promociones', to='usuario.categoria')),
                ('productos', models.ManyToManyField(blank=True, help_text='Aplica esta promoción solo a estos productos.', related_name='promociones', to='usuario.producto')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_fin'],
            },
        ),
    ]
