# Generated by Django 5.2.7 on 2025-11-08 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='calificacion_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calificación promedio (de 1 a 5), calculada automáticamente.', max_digits=3),
        ),
        migrations.AddField(
            model_name='producto',
            name='total_resenas',
            field=models.PositiveIntegerField(default=0, help_text='Número total de reseñas, calculado automáticamente.'),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(help_text='Calificación del 1 al 5.')),
                ('titulo', models.CharField(help_text="Título de la reseña (ej: 'Excelente producto')", max_length=200)),
                ('comentario', models.TextField(help_text='Cuerpo de la reseña.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuario.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('producto', 'usuario')},
            },
        ),
    ]
